additionalProperties:
  npmName:  "@aicpa-ads/auditdata-model"
  npmVersion: 0.0.0-beta
  projectDescription: The purpose of the Audit Data API Working Group (Working Group) is to define an API standard for the transfer of financial audit data between two systems. The standard is open and licensed under an MIT license. Participation in the Working Group and contributions are open to all interested parties. The API standard intends to build upon the standards already developed by the AICPA  and to use the terms defined in that standard where applicable.
  licenseName:  MIT
  infoUrl: https://github.com/AICPA-ADS/AuditData-API

files:
  package-dist.mustache:
    destinationFilename: dist/package.json
  README.mustache:
    destinationFilename: dist/README.md


  