## TODO: return decimals instead of floats

additionalProperties:
  packageName:  Org.Aicpa.AuditData.Client  
  packageDescription: The purpose of the Audit Data API Working Group (Working Group) is to define an API standard for the transfer of financial audit data between two systems. The standard is open and licensed under an MIT license. Participation in the Working Group and contributions are open to all interested parties. The API standard intends to build upon the standards already developed by the AICPA  and to use the terms defined in that standard where applicable.
  licenseId:  MIT
  packageCopyright: AICPA
  packageAuthors: AICPA Audit Data Standards Team
  sourceRepositoryUrl: https://github.com/AICPA-ADS/AuditData-API
  releaseNote: 

  netCoreProjectFile: true
  excludeTests: true
  useRestSharp: true
  useWebRequest: false
  supportsRetry: true
  validatable: false
  targetFramework: netstandard2.0
  useDateTimeOffset: true

files:
  README.mustache:
    destinationFilename: README.md 
  AbstractOpenAPISchema.mustache:
    destinationFilename: src/Org.Aicpa.AuditData.Client/Client/AbstractOpenAPISchema.cs


  